sudo: required

language: ruby

services:
  - docker

script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker run -d --net=host --name consul-standalone consul:v0.7.0 agent -dev -client 0.0.0.0
- dockerTag=mrduguo/docker-gateway ./gradlew
